import { library, dom } from "@fortawesome/fontawesome-svg-core";

import {
  faAnglesRight,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faCircleRight,
  faCircleArrowRight,
  faArrowRight,
  faCheck,
  faCircleCheck,
  faSquareCheck,
  faCircleChevronRight,
  faChevronUp,
  faPenToSquare,
  faEnvelope,
  faCircleExclamation,
  faFile,
  faFolder,
  faFolderOpen,
  faGlobe,
  faHandPointRight,
  faKey,
  faLightbulb,
  faLock,
  faMagnifyingGlass,
  faStar,
  faStarHalfStroke,
  faRotate,
  faXmark,
  faUser,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAnglesRight,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faCircleRight,
  faCircleArrowRight,
  faArrowRight,
  faCheck,
  faCircleCheck,
  faSquareCheck,
  faCircleChevronRight,
  faChevronUp,
  faPenToSquare,
  faEnvelope,
  faCircleExclamation,
  faFile,
  faFolder,
  faFolderOpen,
  faGlobe,
  faHandPointRight,
  faKey,
  faLightbulb,
  faLock,
  faMagnifyingGlass,
  faStar,
  faStarHalfStroke,
  faRotate,
  faXmark,
  faUser,
);

import {
  faClock,
  faFile as faFileRegular,
  faFolder as faFolderRegular,
  faFolderOpen as faFolderOpenRegular,
  faStar as faStarRegular,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faClock,
  faFileRegular,
  faFolderRegular,
  faFolderOpenRegular,
  faStarRegular,
);

import {
  faAmazon,
  faBitbucket,
  faCodepen,
  faDribbble,
  faDropbox,
  faFacebook,
  faFlickr,
  faFoursquare,
  faGetPocket,
  faGithub,
  faGitlab,
  faGoogle,
  faInstagram,
  faLinkedin,
  faMedium,
  faPaypal,
  faPinterest,
  faReddit,
  faSkype,
  faSlack,
  faSlideshare,
  faSnapchat,
  faSpotify,
  faStackOverflow,
  faStripe,
  faTiktok,
  faTumblr,
  faTwitter,
  faVimeo,
  faWordpress,
  faYoutube,
  faLine,
  faAppStore,
  faGooglePlay,
  faTwitch,
  faDiscord,
  faApple,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faAmazon,
  faBitbucket,
  faCodepen,
  faDribbble,
  faDropbox,
  faFacebook,
  faFlickr,
  faFoursquare,
  faGetPocket,
  faGithub,
  faGitlab,
  faGoogle,
  faInstagram,
  faLinkedin,
  faMedium,
  faPaypal,
  faPinterest,
  faReddit,
  faSkype,
  faSlack,
  faSlideshare,
  faSnapchat,
  faSpotify,
  faStackOverflow,
  faStripe,
  faTiktok,
  faTumblr,
  faTwitter,
  faVimeo,
  faWordpress,
  faYoutube,
  faLine,
  faAppStore,
  faGooglePlay,
  faTwitch,
  faDiscord,
  faApple,
);

dom.watch();
